services:
  db:
    image: 'postgres:15'
    container_name: db
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'youruser'
      POSTGRES_PASSWORD: 'yourpassword'
      POSTGRES_DB: 'mydb'
    volumes:
      - db_data:/var/lib/postgresql/data
    stdin_open: true
    tty: true
    networks:
      - my_network

  server:
    build: ./backend/
    container_name: server
    restart: always
    ports:
      - '3000:3000'
    expose:
      - '3000:3000'
    stdin_open: true
    depends_on:
      - db
    tty: true
    volumes:
      - ./backend/:/backend
      - ./backend/prisma:/backend/prisma
    working_dir: /backend
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
